// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEEkRRByUYGcdXejD3xEnuZ7JbG2hSOPg',
    appId: '1:722927574519:web:5e74380666b228c0ea62f2',
    messagingSenderId: '722927574519',
    projectId: 'run-for-money-f042a',
    authDomain: 'run-for-money-f042a.firebaseapp.com',
    storageBucket: 'run-for-money-f042a.firebasestorage.app',
    measurementId: 'G-ZTYLYFDP74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFeBwV9OvN3XUjqyNcpBnH2sDSYZAOOVc',
    appId: '1:722927574519:android:03ed2ceb0f59bb8bea62f2',
    messagingSenderId: '722927574519',
    projectId: 'run-for-money-f042a',
    storageBucket: 'run-for-money-f042a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-YFNgTilGXhQo6skRU_kFf9SlS_NeNA',
    appId: '1:722927574519:ios:3e4988232208675dea62f2',
    messagingSenderId: '722927574519',
    projectId: 'run-for-money-f042a',
    storageBucket: 'run-for-money-f042a.firebasestorage.app',
    iosBundleId: 'com.example.runForMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD-YFNgTilGXhQo6skRU_kFf9SlS_NeNA',
    appId: '1:722927574519:ios:3e4988232208675dea62f2',
    messagingSenderId: '722927574519',
    projectId: 'run-for-money-f042a',
    storageBucket: 'run-for-money-f042a.firebasestorage.app',
    iosBundleId: 'com.example.runForMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEEkRRByUYGcdXejD3xEnuZ7JbG2hSOPg',
    appId: '1:722927574519:web:45eb9414ac79a397ea62f2',
    messagingSenderId: '722927574519',
    projectId: 'run-for-money-f042a',
    authDomain: 'run-for-money-f042a.firebaseapp.com',
    storageBucket: 'run-for-money-f042a.firebasestorage.app',
    measurementId: 'G-4VPD02XVHH',
  );

}